version: "3"
services:
    dbtest:
        container_name: dbtest
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB}
            DATABASE_URL: ${DB_URL_TEST}
        ports:
            - 5432:5432
        restart: always
    project-service-test:
        container_name: project-service-test
        environment:
            ENVIRONMENT: test
            DATABASE_URL: ${DB_URL_TEST}
        build:
            context: ${PROJECT_PATH}/
        ports:
            - 3000:3000
        depends_on:
            - dbtest
        volumes:
            - ./${PROJECT_PATH}:/app
            - /app/node_modules
        command:
          [
              "./wait-for-it.sh",
              "dbtest:5432",
              "--",
              "npm",
              "run",
              "start-dev"
          ]
    user-service-test:
        container_name: user-service-test
        environment:
            ENVIRONMENT: test
        build:
            context: ${USER_PATH}/
            dockefile: test.Dockerfile
        ports:
            - 3001:3001
        depends_on:
            - dbtest
        volumes:
            - ./${USER_PATH}:/app
            - /app/node_modules
    api-gateway-test:
        container_name: api-gateway-test
        environment:
            ENVIRONMENT: test
        build:
            context: .
            dockerfile: dev.Dockerfile
        ports:
            - "3004:3004"
        volumes:
            - ./:/app
            - /app/node_modules
