version: "3"
services:
    user-service-test:
        container_name: user-service-test
        environment:
            ENVIRONMENT: test
        build:
            context: ${USER_PATH}/
            dockerfile: dev.Dockerfile
        ports:
            - "3001:3001"
        volumes:
            - ./${USER_PATH}:/app
            - /app/node_modules
        networks:
            - puma-network-test
        command:
          [
              "./wait-for-it.sh",
              "localhost:5432",
              "--",
              "npm",
              "run",
              "start-dev"
          ]

    # frontend-test:
    #     container_name: frontend-test
    #     environment:
    #         ENVIRONMENT: test
    #     build:
    #         context: ../${FRONT_PATH}/puma
    #         dockerfile: dev.Dockerfile
    #     ports:
    #         - "8080:8080"
    #     volumes:
    #         - ../${FRONT_PATH}/puma:/app
    #         - /app/node_modules
    #     networks:
    #         - puma-network-test

networks:
    puma-network-test:
