name: CI

on:
  push:
    branches: 
      - dev
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
      USER_PATH: 2022-2-PUMA-UserService 
      PROJECT_PATH: 2022-2-PUMA-ProjectService
      DB_USER: pumaadmin
      DB_PASS: pumaadmin
      DB: puma
      
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    
    - name: check userService
      uses: actions/checkout@v3
      with:
        repository: fga-eps-mds/2022-2-PUMA-UserService
        path: 2022-2-PUMA-UserService
    
    - name: check projectService
      uses: actions/checkout@v3
      with:
        repository: fga-eps-mds/2022-2-PUMA-ProjectService
        path: 2022-2-PUMA-ProjectService
    
    #- name: Build and up containers
    #  run: docker-compose -f test.actions.docker-compose.yaml up -d
      
    #- name: Run tests
    #  run: docker exec api-gateway-test npm run test-coverage
    
    - name: Run make
      run: |
          sudo docker-compose -f test.docker-compose.yaml up --build -d 
	        sudo chmod +x ./tests/utils/db_script_test.sh ./tests/utils/wait-for-it-test.sh ./tests/utils/db_init_test.sh && (./tests/utils/wait-for-it-test.sh dbtest:5432 -- true && ./tests/utils/db_init_test.sh);

    - name: Run test
      run: |
          sudo docker-compose -f test.docker-compose.yaml exec api-gateway-test npm run test-coverage
	        sudo docker-compose -f test.docker-compose.yaml down
          
    - name: Setup tmate session
      if: success() || failure()
      uses: mxschmitt/action-tmate@v3

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
