name: CI

on:
  push:
    branches: 
      - dev
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        
    - name: check userService
      uses: actions/checkout@v3
      with:
        repository: fga-eps-mds/2022-2-PUMA-UserService
        path: 2022-2-PUMA-UserService
    
    - name: check projectService
      uses: actions/checkout@v3
      with:
        repository: fga-eps-mds/2022-2-PUMA-ProjectService
        path: 2022-2-PUMA-ProjectService

    - name: Build and up containers
      run: docker-compose -f test.actions.docker-compose.yaml up -d
      env:
        USER_PATH: 2022-2-PUMA-UserService 
        PROJECT_PATH: 2022-2-PUMA-ProjectService
        DB_USER: pumaadmin
        DB_PASS: pumaadmin
        DB: puma
        DB_URL_TEST: postgres://pumaadmin:pumaadmin@dbtest:5432/puma
    
    - name: Create and Populate Database
      run: | 
          sudo docker cp ./tests/utils/db_drop.sql dbtest:/db_drop.sql
          sudo docker exec dbtest psql -U pumaadmin -d puma -f /db_drop.sql
          sudo docker cp ./tests/utils/db_create.sql dbtest:/db_create.sql 
          sudo docker exec dbtest psql -U pumaadmin -d puma -f /db_create.sql
          sudo docker cp ./tests/utils/db_populate.sql dbtest:/db_populate.sql
          sudo docker exec dbtest psql -U pumaadmin -d puma -f /db_populate.sql
   
    - name: Run tests
      run: docker exec api-gateway-test npm run test-coverage

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
