name: CI

on:
  push:
    branches: 
      - dev
  pull_request:
    types: [opened, reopened, edited]
env:
  USER_PATH: 2022-2-PUMA-UserService

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        
    - name: check userService
      uses: actions/checkout@v3
      with:
        repository: fga-eps-mds/2022-2-PUMA-UserService
        path: 2022-2-PUMA-UserService
    
    - name: test userService files
      run: cat ../${USER_PATH}/dev.Dockerfile

    - name: Run npm install
      run: npm install

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
